name = "LockPatternComplexity"
uuid = "543c5b92-ecbf-4ab6-ab9f-9ddc949b5521"
authors = ["Jaan Tollander de Balsch"]
version = "0.4.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
