name = "LockPatternComplexity"
uuid = "543c5b92-ecbf-4ab6-ab9f-9ddc949b5521"
authors = ["Jaan Tollander de Balsch"]
version = "0.0.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
